services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgres/data
  mongodb:
    image: mongo
    environment:
     - MONGO_INITDB_ROOT_USERNAME=root 
     - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
     - 27017:27017
    volumes:
     - mongodata:/var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
     - rabbitmqdata:/var/lib/rabbitmq/data  
  product-svc:
    image: bugrakiziltas/product-svc:latest
    build:
      context: .
      dockerfile: src/ProductService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Rabbitmq__Host=rabbitmq
      - ConnectionStrings__DbConnection=Server=postgres:5432;User Id=postgres; Password=postgrespw; Database=Products
      - IdentityUrl=http://identity-svc
      - Role=http://schemas.microsoft.com/ws/2008/06/identity/claims/role
    ports:
      - 5000:80
    depends_on:
      - postgres
      - rabbitmq
  search-svc:
    image: bugrakiziltas/search-svc:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Rabbitmq__Host=rabbitmq
      - ConnectionStrings__ConnectionString=mongodb://root:mongopw@mongodb
      - OrderServiceUrl=http://order-svc
      - ProductServiceUrl=http://product-svc
      - Role=http://schemas.microsoft.com/ws/2008/06/identity/claims/role
    ports:
      - 5001:80
    depends_on:
      - mongodb
      - rabbitmq   
  identity-svc:
    image: bugrakiziltas/identity-svc:latest
    build:
      context: .
      dockerfile: src/IdentityServerAspNetIdentity/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres; Password=postgrespw; Database=IdentityServer
    ports:
      - 5005:80
    depends_on:
      - postgres
  gateway-svc:
    image: bugrakiziltas/gateway-svc:latest
    build:
      context: .
      dockerfile: src/Gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 5006:80
  order-svc:
    image: bugrakiziltas/order-svc:latest
    build:
      context: .
      dockerfile: src/OrderService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Rabbitmq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres; Password=postgrespw; Database=OrderDB
    ports:
      - 5009:80
    depends_on:
      - postgres
      - rabbitmq
  shoppingcart-svc:
    image: bugrakiziltas/shoppingcart-svc:latest
    build:
      context: .
      dockerfile: src/ShoppingCartService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DbConnection=Server=postgres:5432;User Id=postgres; Password=postgrespw; Database=ShoppingCart
      - Url=http://identity-svc
      - Role=http://schemas.microsoft.com/ws/2008/06/identity/claims/role
      - StripeUrl=http://stripe-svc
      - Email=http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
    ports:
      - 5007:80
    depends_on:
      - postgres
  stripe-svc:
    image: bugrakiziltas/stripe-svc:latest
    build:
      context: .
      dockerfile: src/StripeService/Dockerfile
    env_file:
      - .env  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Rabbitmq__Host=rabbitmq
      - ConnectionStrings__DbConnection=Server=postgres:5432;User Id=postgres; Password=postgrespw; Database=StripeDB
      - Stripe__SecretKey=${STRIPE_SECRET_KEY}
      - Stripe__WHKey=${STRIPE_WH_KEY}
    ports:
      - 5008:80
    depends_on:
      - postgres
      - rabbitmq

volumes:
  pgdata:
  mongodata:
  rabbitmqdata:
  product-svc:
  search-svc:
  identity-svc:
  gateway-svc:
  order-svc:
  shoppingcart-svc:
  stripe-svc:      